apiVersion: v1
kind: Service
metadata:
  name: students-update-service
spec:
  selector:
    app: students-update-service
  ports:
    - protocol: TCP
      port: 8084
      nodePort: 30084 
      targetPort: 8084
  type: NodePort 